### ISSUE TITLE
error on build

### ISSUE THREAD

**Issue by papanomad535** [tonlabs/tonos-cli#104]
Compiling ton_sdk v1.6.3 (https://github.com/tonlabs/TON-SDK.git#4d34e4d5)
error[E0599]: no function or associated item named `get_pubkey` found for struct `ton_abi::Contract` in the current scope
   --> /home/ton/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/4d34e4d/ton_sdk/src/contract.rs:143:25
    |
143 |         Ok(AbiContract::get_pubkey(data)?
    |                         ^^^^^^^^^^ function or associated item not found in `ton_abi::Contract`

error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
   --> /home/ton/.cargo/git/checkouts/ton-sdk-11823a0ea1fdf592/4d34e4d/ton_sdk/src/contract.rs:144:19
    |
144 |             .map(|pub_key| PublicKey::from_bytes(&pub_key))
    |                   ^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `[u8]`
    = help: unsized locals are gated as an unstable feature
help: function arguments must have a statically known size, borrowed types always have a known size
    |
144 |             .map(|&pub_key| PublicKey::from_bytes(&pub_key))
    |                   ^

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `ton_sdk`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by joydark** [comment]
Thank you for your report.
Please use _cargo update && cargo build --release_ to compiling ton_sdk v1.6.3 (https://github.com/tonlabs/TON-SDK.git#4d34e4d5)
