### ISSUE TITLE
DeBot Terminal.inputStr multiline doesn't stop on CTRL+D on windows

### ISSUE THREAD

**Issue by NoamDev** [tonlabs/tonos-cli#106]

**Comment by joydark** [comment]
Thank you for your report. We will update documentation.

On Windows your can use Ctrl+Z.

**Comment by NoamDev** [comment]
@joydark 
It's no only a documentation bug, but an implementation one too (kinda).
The following line needs to be changed so that it'll print "CTRL+Z" on windows:
 https://github.com/tonlabs/tonos-cli/blob/7fe1628769a3060d6c26f7a47de836de31f6953f/src/debot/interfaces/terminal.rs#L104
