### ISSUE TITLE
Support 'endpoints' in tonos-cli.conf.json

### ISSUE THREAD

**Issue by SkySonR** [tonlabs/tonos-cli#111]
According to https://github.com/tonlabs/TON-SDK/blob/master/docs/mod_client.md#NetworkConfig it's possible to specify multiple DApp Server URLs in SDK, but in tonos-cli is not. Could you please assist?

**Comment by SkySonR** [comment]
UPD: for those who want to have this functionality right now you can use our super dirty patch which brokes 'url' but enable support of endpoints https://github.com/INTONNATION/tonos-cli/commit/37ee1208c95e9c98b8ff8a333541927e63fb43c5

To build this version:
git clone  https://github.com/INTONNATION/tonos-cli.git
cargo build --release -j8
mv target/release/tonos-cli /usr/bin/tonos-cli

tonos-cli.conf.json example: 
{"endpoints": ["https://rustnet.ton.dev","https://intonnation.freetondapps.com"], "wc":0,"addr":null,"wallet":null,"abi_path":null,"keys_path":null,"retries":5,"timeout":60000,"is_json":false,"depool_fee":0.5}

Done without knowelenge of Rust, maybe someone can rework and make pull request.

**Comment by Keshoid** [comment]
We added support for custom endpoints. Starting from v0.16.1 .

**Comment by SkySonR** [comment]
> We added support for custom endpoints. Starting from v0.16.1 . Please, check.

Will check today and reply.  Many thanks

**Comment by SkySonR** [comment]
@Keshoid it's does not work, currently rustnet.ton,dev down, rustnet1.ton.dev down, rustnet2.ton.dev works 

TONOS-CLI will all endpoints set cannot automaticly detect this and switch to rustnet2.ton.dev

**Comment by Keshoid** [comment]
tonos-cli passes all endpoints to sdk so it might be an issue of sdk.
