### ISSUE TITLE
tonos-cli arguments and config

### ISSUE THREAD

**Issue by BoogerWooger** [tonlabs/tonos-cli#14]
Writing scripts, automating the execution of ```tonos-cli``` I encountered a problem - not all parameters, allowed to set in config (```./tonlabs-cli.conf.json```) can be set from command line, for example ```--url "https://main.ton.dev"```

Also - not all parameters from command line (for example address) cannot be transparently set in ```./tonlabs-cli.conf.json``` (in command line we use full address ```-1:XXXXXX...```, while in ```./tonlabs-cli.conf.json``` we need to use separately workchain and address (keys ```wc``` and ```addr```).

What behaviour I expect: 

1) If I set everything in ```./tonlabs-cli.conf.json``` I want to use it like ```./tonos-cli run getTransactions '{}'``` without ```address```, ```url```, ```abi``` and ```keys``` totally

2) If I don't want to use config I need the ability to set EVERY parameter in command line, including ```url``` like ```./tonos-cli run --url "https://main.ton.dev" --abi "SafeMultisigwallet.abi.json" --keys "./mysecret.keys.json" -1:ab1f1e8daf784ba59d9ae6266bbadda7a0b63a1d5d38eed5c9a11161861eb1cd getTransactionIds '{}' ```

P.S. Maybe it's good to name every parameter, including ```address```, ```method```, and ```params``` to avoid any wrong readings in automating tasks with ```tonos-cli```, like ```./tonos-cli run --url "https://main.ton.dev" --abi "SafeMultisigwallet.abi.json" --keys "./mysecret.keys.json" --address "-1:ab1f1e8daf784ba59d9ae6266bbadda7a0b63a1d5d38eed5c9a11161861eb1cd" --method getTransactionIds --params '{}' ```  but I'm not sure.

**Comment by Keshoid** [comment]
Since 0.1.9 version you can define `--url` param before every subcommand. Also there is a `callex` subcmd in which you can define function argument like `--param_name param_value`. See readme for details.
