### ISSUE TITLE
add nanotons flag to the tonos-cli.conf.json

### ISSUE THREAD

**Issue by depool-live** [tonlabs/tonos-cli#148]
please add flag "nanotons": true/false to the tonos-cli.conf.json
to work with tonos-cli without dot or gap in account balance

**Comment by SilkovAlexander** [comment]
Hello, we've got such flag ` --delimiters <USE_DELIMITERS>    Use delimiters while printing account balance`
Use command 
```
 tonos-cli config --delimiters false
```
to return nanoton view of the balance
