### ISSUE TITLE
commit 42621a5333f24642e8e8779eb851f34aa51588ae  error on build

### ISSUE THREAD

**Issue by Custler** [tonlabs/tonos-cli#164]
git pull --recurse-submodules
$ git show
commit 42621a5333f24642e8e8779eb851f34aa51588ae (HEAD -> master, origin/master, origin/HEAD)
Merge: 5eee991 8e35b83
Author: Sergei Voronezhskii <76666924+d3p@users.noreply.github.com>
Date:   Wed May 19 07:45:51 2021 +0300
    Merge pull request #163 from tonlabs/sdk-1.15.0-rc
    Update to sdk 1.15.0

$ cargo update
    Updating crates.io index
    Updating git repository `https://github.com/tonlabs/ton-labs-abi.git`
    Updating git repository `https://github.com/tonlabs/ton-labs-block.git`
    Updating git repository `https://github.com/tonlabs/TON-SDK.git`
error: failed to get `ton_client` as a dependency of package `tonos-cli v0.13.1 (/usr/home/svt/Rnode-scripts/tonos-cli)`

Caused by:
  failed to load source for dependency `ton_client`

Caused by:
  Unable to update https://github.com/tonlabs/TON-SDK.git?branch=1.15.0-rc

Caused by:
  failed to find branch `1.15.0-rc`

Caused by:
  cannot locate remote-tracking branch 'origin/1.15.0-rc'; class=Reference (4); code=NotFound (-3)

**Comment by joydark** [comment]
Thanks you. Fixed
