### ISSUE TITLE
tonos-cli config path should be consistent

### ISSUE THREAD

**Issue by joe-bowman** [tonlabs/tonos-cli#20]
Instead of the current directory, `tonlabs-cli.conf.json` should be written to a consistent path for a given user of a given system. for example: `~/.tonos-cli/tonlabs-cli.conf.json` so that tonos-cli can  be run from any directory on the system and yield consistent results.

Similarly, .tvc and .abi files could live in a subdir of the same path to save referencing them on every call.

**Comment by user529** [comment]
Yeah! I rise in strong support for that!

**Comment by Keshoid** [comment]
Done. Since 0.1.9 version you can define path to config file using env variable or cmd line option `--config`.
