### ISSUE TITLE
Doesn't work since version 1.1.12 on ubuntu 16.04, 18.04

### ISSUE THREAD

**Issue by ch1seL** [tonlabs/tonos-cli#35]
I build tonos-cli from master branch and since version 1.1.12 tonos-cli throws error "tonos-cli: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by tonos-cli)" on Ubuntu 16.04, 18.04

https://github.com/ton-actions/setup-tools/runs/922097272?check_suite_focus=true

**Comment by BorisI** [comment]
That's right, Ubuntu 16.04 ships glibc 2.23, 18.04 ships glibc 2.27, 20.04 ships glibc 2.31. The target configuration is 18.04, so it's recommended to stick to glibc 2.27.

**Comment by ch1seL** [comment]
some kind of false positive 😟
