### ISSUE TITLE
error: Found argument '-1' which wasn't expected, or isn't valid in this context

### ISSUE THREAD

**Issue by anvme** [tonlabs/tonos-cli#44]
instruction https://docs.ton.dev/86757ecb2/p/37a848-run-depool/t/689e45
If stake was from master 
Command
./tonos-cli depool --addr 0:dddd.....dddd withdraw on --wallet "-1:123...abc" --sign "xxx"

we get error
error: Found argument '-1' which wasn't expected, or isn't valid in this context

USAGE:
    tonos-cli depool withdraw on --wallet <MSIG>

For more information try --help

**Comment by joydark** [comment]
Sorry for late response.
Fixed in current version tonos-cli
