### ISSUE TITLE
Fix json format out for active account

### ISSUE THREAD

**Issue by ilyar** [tonlabs/tonos-cli#518]
`npx tonos-cli --json account 0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201`

**Actual:**
```shell
{
  "0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201": {
    "acc_type": "Active",
    "address": "0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201",
    "balance": "100000000000",
    "last_paid": "1644230193",
    "last_trans_lt": "0x15",
    "data(boc)": "b5ee9c720101020100980001dff869eb226d1d3eda3b9863e3121b66b351cbf8c6ce7f4fd4dba45901b97155d70000017ed3c1ae58fc34f591368e9f6d1dcc31f1890db359a8e5fc63673fa7ea6dd22c80dcb8aaeb80000000000000000000000000000000000000000000000000000000000000002020000000001018010045a01f0d3d644da3a7db47730c7c62436cd66a397f18d9cfe9fa9b748b20372e2abae010",
    "code_hash": "207dc560c5956de1a2c1479356f8f3ee70a59767db2bf4788b1d61ad42cdad82"
  }
}
```

**Expect:**

```shell
{
  "acc_type": "Active",
  "address": "0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201",
  "balance": "100000000000",
  "last_paid": "1644230193",
  "last_trans_lt": "0x15",
  "data(boc)": "b5ee9c720101020100980001dff869eb226d1d3eda3b9863e3121b66b351cbf8c6ce7f4fd4dba45901b97155d70000017ed3c1ae58fc34f591368e9f6d1dcc31f1890db359a8e5fc63673fa7ea6dd22c80dcb8aaeb80000000000000000000000000000000000000000000000000000000000000002020000000001018010045a01f0d3d644da3a7db47730c7c62436cd66a397f18d9cfe9fa9b748b20372e2abae010",
  "code_hash": "207dc560c5956de1a2c1479356f8f3ee70a59767db2bf4788b1d61ad42cdad82"
}
```

**Mtotivation:**

`npx tonos-cli --json account 0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201 | jq .acc_type `

**Comment by SkySonR** [comment]
> ```shell
> {
>   "0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201": {
>     "acc_type": "Active",
>     "address": "0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201",
>     "balance": "100000000000",
>     "last_paid": "1644230193",
>     "last_trans_lt": "0x15",
>     "data(boc)": "b5ee9c720101020100980001dff869eb226d1d3eda3b9863e3121b66b351cbf8c6ce7f4fd4dba45901b97155d70000017ed3c1ae58fc34f591368e9f6d1dcc31f1890db359a8e5fc63673fa7ea6dd22c80dcb8aaeb80000000000000000000000000000000000000000000000000000000000000002020000000001018010045a01f0d3d644da3a7db47730c7c62436cd66a397f18d9cfe9fa9b748b20372e2abae010",
>     "code_hash": "207dc560c5956de1a2c1479356f8f3ee70a59767db2bf4788b1d61ad42cdad82"
>   }
> }
> ```

| jq .[].acc_type ?

**Comment by ilyar** [comment]
**Solution:** `npx tonos-cli --json account 0:c3da3e141096b5bb518b3479b8fe36163c191e2aaffa5c603b85b62335c91201 | jq -r .[]`
@SkySonR thx
