### ISSUE TITLE
inner error recursion limit exceeded at line 1 column 29630

### ISSUE THREAD

**Issue by user529** [tonlabs/tonos-cli#70]
I noticed the issue which occurs in case participant list is big enough. More than 125 participants.
So, then you try to run something like:
> tonos-cli --config ~/tonlabs-cli.conf.json runget -1:3333333333333333333333333333333333333333333333333333333333333333 participant_list_extended

You will have some part of output, but it will fail with the following error:
> ```
> inner error recursion limit exceeded at line 1 column 29630
> Error: 1
> ```

Please also find the version of tonos-cli was used:
> tonos_cli 0.1.27
> COMMIT_ID: 688175208033ae46900b24c06944c14bb248b808
> BUILD_DATE: 2020-11-27 14:26:44 +0100
> COMMIT_DATE: 2020-11-24 16:50:35 +0300
> GIT_BRANCH: master

**Comment by joydark** [comment]
Seems to fixed with SDK updates. Checked on main.ton.dev
