### ISSUE TITLE
Cannot pass data (static variables) when deploying contract

### ISSUE THREAD

**Issue by pizza-777** [tonlabs/tonos-cli#705]
Can I pass data (static variables) when deploying contract with tonos-cli?
If not, please add this ability.

**Comment by SilkovAlexander** [comment]
Yes you can with tonos-cli `genaddr` command. It was poorly described in readme, I have updated it.
https://github.com/tonlabs/tonos-cli/tree/SilkovAlexander/update_readme#41-generate-contract-address
Just use `--data <data>` and `--save` options
