### ISSUE TITLE
tonos-cli message does not access address as first argument

### ISSUE THREAD

**Issue by joe-bowman** [tonlabs/tonos-cli#8]
**Bug**

When executing `tonos-cli message <wc_-1_addr>...` the -1 of a non workchain -1 address is interpreted as flag. We can work around this with by ensuring all flags are moved the beginning of the command, and using -- before the -1 to escape the flag - however, I believe this can be resolved with a single line change.

Insert a new line before Line 151 of main.rs, with the following code:

`(@setting AllowLeadingHyphen)`

I would happily create a PR, but due to another issue, I am currently unable to compile tonos-cli to test :)

**Comment by Keshoid** [comment]
Fixed.
