### ISSUE TITLE
Error: debot fetch 0:52a955ec2c5a80cf6a4c42c9ec00dcb70fde2bd319d88e38edd5013749978113

### ISSUE THREAD

**Issue by papanomad535** [tonlabs/tonos-cli#81]
tonos_cli 0.1.29
COMMIT_ID: 3976b22ba78b503265994474cc5156a288b12340
BUILD_DATE: 2020-12-14 14:51:15 +0000
COMMIT_DATE: 2020-12-14 17:48:30 +0300
GIT_BRANCH: master

./tonos-cli --url https://main.ton.dev debot fetch 0:52a955ec2c5a80cf6a4c42c9ec00dcb70fde2bd319d88e38edd5013749978113

debash$ failed to read line: Resource temporarily unavailable (os error 11)

**Comment by joydark** [comment]
Checked. Right now it's ok. Please reopen issue if it repeats again
