### ISSUE TITLE
Error at debot fetch command

### ISSUE THREAD

**Issue by vilija19** [tonlabs/tonos-cli#87]
Hi.
I've got an error at command - 
`tonos-cli debot fetch 0:5d1ca0ead13e6a4994074d2aaaee64ae925cc94858467bb2170de972a1835435`

Error is:
`debash$ failed to read line: Resource temporarily unavailable (os error 11)`

```
OS - Linux
tonos-cli 0.2.0
"url": "https://net.ton.dev"
```

From the same host `tonos-cli 0.1.29` works fine with the same command
Thanks.

**Comment by pathflores** [comment]
-Message#👋General
Message#😁General-

**Comment by joydark** [comment]
Thank you for your report.
Connections updated in version ^0.6 Please update to newest version tonos-cli
