### ISSUE TITLE
Can't build on FreeBSD

### ISSUE THREAD

**Issue by tarkhil** [tonlabs/tonos-cli#902]
Hello

FreeBSD 13.1, amd64

rustc 1.66.1 (90743e729 2023-01-10) (built from a source tarball)

cargo build fails with

[syntax errors](https://pastebin.com/89vQDth2)

**Comment by BorisI** [comment]
Hi there,

I've just build it successfully on 13.1 (with rustc 1.67.1, not sure it matters though). the list of ingredients doesn't look right:
...
line 93:  Compiling ton_types v1.12.6 (https://github.com/tonlabs/ton-labs-types.git?tag=1.12.6#8e218813)
...
line 140:  Compiling ton_types v1.12.7 (https://github.com/tonlabs/ever-types.git?tag=1.12.7#5acf1cc4)
...
line 209: Compiling ton_types v1.12.7 (https://github.com/tonlabs/ton-labs-types.git#5acf1cc4)
...

tonos-cli uses Cargo.lock file to manage dependencies, make sure to fetch it from the repository as well.

**Comment by Keshoid** [comment]
Try to build from latest sources. It should be compiled successfully. Checked.
