### ISSUE TITLE
crash on tonos-cli run

### ISSUE THREAD

**Issue by depool-live** [tonlabs/tonos-cli#93]
root@rnode:/ton-node/tools# ./tonos-cli version
Config: /ton-node/tools/tonos-cli.conf.json
tonos-cli 0.2.1
COMMIT_ID: 1e7d9fe04894b37e82ecaf7e04ae15e189bb791c
BUILD_DATE: 2021-01-25 21:45:21 +0000
COMMIT_DATE: 2021-01-25 22:08:42 +0300
GIT_BRANCH: update_last_depool
root@rnode:/ton-node/tools# /ton-node/tools/tonos-cli run -1:3333333333333333333333333333333333333333333333333333333333333333 compute_returned_stake '{"wallet_addr":"0x"}' --abi /ton-node/configs/Elector.abi.json
Config: /ton-node/tools/tonos-cli.conf.json
Input arguments:
 address: -1:3333333333333333333333333333333333333333333333333333333333333333
  method: compute_returned_stake
  params: {"wallet_addr":"0x"}
     abi: /ton-node/configs/Elector.abi.json
    keys: None
lifetime: None
  output: None
Connecting to "https://rustnet.ton.dev"
Generating external inbound message...

MessageId: 4b6c59e74d7ea6287630051b251805867a7611b3582b234534e19b19b6948342
Expire at: unknown
Running get-method...
thread 'main' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.10/src/into_url.rs:44:14

**Comment by depool-live** [comment]
not from docker work fine

**Comment by depool-live** [comment]
tonic-cli 0.3.0 crash on run always

**Comment by joydark** [comment]
> tonic-cli 0.3.0 crash on run always

fixed in 0.3.2 run with address without workchain
