### ISSUE TITLE
build error on ton_client

### ISSUE THREAD

**Issue by depool-live** [tonlabs/tonos-cli#99]
macOS 10.13.6
tonos-cli 0.3.0

error: reached the type-length limit while instantiating `tokio::loom::std::unsafe_cell::U...<T, S>::dealloc::{{closure}}#1]>`
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/loom/std/unsafe_cell.rs:13:5
   |
13 | /     pub(crate) fn with_mut<R>(&self, f: impl FnOnce(*mut T) -> R) -> R {
14 | |         f(self.0.get())
15 | |     }
   | |_____^
   |
   = note: consider adding a `#![type_length_limit="1149087"]` attribute to your crate

error: aborting due to previous error

error: could not compile `ton_client`.

**Comment by joydark** [comment]
Would you please check your rust version?
It' seems you have an old one.

**Comment by joydark** [comment]
Would you please check your rust version?
It' seems you have an old one.
Checked on rust 1.49.0. If it's up to date, I'll reopen issue
